---
title: "Store_clusters_mktshare_sales"
author: "Anneke Speijers"
date: "30 May 2016"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, fig.width=15, fig.height =15}

setwd("~/Desktop/BGSE/Term3/MasterProject/GSE")

#load packages
library(ggplot2)
library(data.table)
library(grid)
library(gridExtra)

# read in tables
cluster_store <- as.data.table(readRDS("storeID_cluster_mktshare_sales.RData"))
cluster_store$storeID <- as.integer(as.character(cluster_store$storeID))
master_train <- readRDS("master_train_mktshare.RData")

# join
clusters <- merge(master_train, cluster_store, by="storeID", all.x=TRUE)
rm(master_train, cluster_store)

# change necessary columns to factors
factor_vars <- c("productID", "storeID", "grup", "fam", "subFam", "sub_chain",
                 "chain", "town", "size", "community", "province", "units", 
                 "flavor", "type", "fit.cluster")
clusters <- clusters[,(factor_vars):=lapply(.SD, as.factor), .SDcols=factor_vars, with=FALSE]


# plots - store vars - counts of stores
plot1 <- ggplot(clusters, aes_string("fit.cluster", fill="sub_chain")) + geom_bar() + ggtitle("sub_chain") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
plot2 <- ggplot(clusters, aes_string("fit.cluster", fill="chain")) + geom_bar()  + ggtitle("chain") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
plot3 <- ggplot(clusters, aes_string("fit.cluster", fill="size")) + geom_bar()  + ggtitle("size") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
plot4 <- ggplot(clusters, aes_string("fit.cluster", fill="town")) + geom_bar() + theme(legend.position="none")  + ggtitle("town") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
plot5 <- ggplot(clusters, aes_string("fit.cluster", fill="province")) + geom_bar() + theme(legend.position="none") + ggtitle("province") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
plot6 <- ggplot(clusters, aes_string("fit.cluster", fill="community")) + geom_bar()  + ggtitle("community") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())

grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol=2)
```

```{r, echo=FALSE, fig.width=8, fig.height=8}
# investigate sub_chains appearing in cluster 2
setwd("~/Desktop/BGSE/Term3/MasterProject/GSE")

stores <- readRDS("stores.RData")
large_stores <- stores[size %in% c("Z1", "Z2")]
print("Distribution of subchains within large stores (Z1 and Z2)")
table(large_stores$sub_chain)
hist(large_stores$sub_chain, main = "subchains within store sizes Z1 and Z2")
```
